version: "3.9"

networks:
  web:
    name: backend
    driver: bridge

    
services:  

  nginx:
    image: nginx
    depends_on:
      - evo
    volumes:
      - ./nginx/data/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/data/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - web


























  # nginx:
  #   container_name: nginx
  #   depends_on:
  #     - evolution
  #   restart: always
  #   build: 
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - 80:80
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.5"
  #         memory: "256M"
  #   networks:
  #     - network_aplication

  